name: workquora_client
description: WorkQuora - Find & Hire Nearby Workers
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.2
  provider: ^6.1.1
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  go_router: ^13.2.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  pinput: ^3.0.1
  cupertino_icons: ^1.0.6
  socket_io_client: ^2.0.3+1
  geolocator: ^11.0.0
  fluttertoast: ^8.2.4
  image_picker: ^1.0.7
  intl: ^0.19.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
